// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/config.dart';
import 'api/probe.dart';
import 'api/protocol.dart';
import 'dart:async';
import 'dart:convert';
import 'dto/profile.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 336940439;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'liostunnel_ffi',
        ioDirectory: '../crates/liostunnel-ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiConfigCheckProfile({required ProfileDto dto});

  Future<IncomingDto> crateApiProtocolDecodeMessage({required String line});

  Future<ProbeDto> crateApiProbeEchoProbe({required ProbeDto input});

  Future<String> crateApiProtocolEncodeRequest({required RequestDto req});

  Future<String> crateApiConfigExportProfile({required ProfileDto dto});

  Future<ProfileDto> crateApiConfigImportSsUri({required String uri});

  Future<String> crateApiConfigNewProfileId();

  Future<List<String>> crateApiConfigOfferedCiphers();

  Future<ProfileDto> crateApiConfigParseProfile({required String json});

  Future<String> crateApiConfigProfileSummary({required ProfileDto dto});

  Future<int> crateApiProtocolProtocolVersion();

  Future<String> crateApiConfigSsUriPassword({required String uri});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiConfigCheckProfile({required ProfileDto dto}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile_dto(dto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConfigCheckProfileConstMeta,
        argValues: [dto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigCheckProfileConstMeta =>
      const TaskConstMeta(debugName: "check_profile", argNames: ["dto"]);

  @override
  Future<IncomingDto> crateApiProtocolDecodeMessage({required String line}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(line, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_incoming_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolDecodeMessageConstMeta,
        argValues: [line],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolDecodeMessageConstMeta =>
      const TaskConstMeta(debugName: "decode_message", argNames: ["line"]);

  @override
  Future<ProbeDto> crateApiProbeEchoProbe({required ProbeDto input}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_probe_dto(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_probe_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProbeEchoProbeConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeEchoProbeConstMeta =>
      const TaskConstMeta(debugName: "echo_probe", argNames: ["input"]);

  @override
  Future<String> crateApiProtocolEncodeRequest({required RequestDto req}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_request_dto(req, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolEncodeRequestConstMeta,
        argValues: [req],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolEncodeRequestConstMeta =>
      const TaskConstMeta(debugName: "encode_request", argNames: ["req"]);

  @override
  Future<String> crateApiConfigExportProfile({required ProfileDto dto}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile_dto(dto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConfigExportProfileConstMeta,
        argValues: [dto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigExportProfileConstMeta =>
      const TaskConstMeta(debugName: "export_profile", argNames: ["dto"]);

  @override
  Future<ProfileDto> crateApiConfigImportSsUri({required String uri}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConfigImportSsUriConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigImportSsUriConstMeta =>
      const TaskConstMeta(debugName: "import_ss_uri", argNames: ["uri"]);

  @override
  Future<String> crateApiConfigNewProfileId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigNewProfileIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigNewProfileIdConstMeta =>
      const TaskConstMeta(debugName: "new_profile_id", argNames: []);

  @override
  Future<List<String>> crateApiConfigOfferedCiphers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigOfferedCiphersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigOfferedCiphersConstMeta =>
      const TaskConstMeta(debugName: "offered_ciphers", argNames: []);

  @override
  Future<ProfileDto> crateApiConfigParseProfile({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConfigParseProfileConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigParseProfileConstMeta =>
      const TaskConstMeta(debugName: "parse_profile", argNames: ["json"]);

  @override
  Future<String> crateApiConfigProfileSummary({required ProfileDto dto}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile_dto(dto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigProfileSummaryConstMeta,
        argValues: [dto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigProfileSummaryConstMeta =>
      const TaskConstMeta(debugName: "profile_summary", argNames: ["dto"]);

  @override
  Future<int> crateApiProtocolProtocolVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolProtocolVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolProtocolVersionConstMeta =>
      const TaskConstMeta(debugName: "protocol_version", argNames: []);

  @override
  Future<String> crateApiConfigSsUriPassword({required String uri}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConfigSsUriPasswordConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigSsUriPasswordConstMeta =>
      const TaskConstMeta(debugName: "ss_uri_password", argNames: ["uri"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConnectParamsDto dco_decode_box_autoadd_connect_params_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_connect_params_dto(raw);
  }

  @protected
  ProbeDto dco_decode_box_autoadd_probe_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_probe_dto(raw);
  }

  @protected
  ProfileDto dco_decode_box_autoadd_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile_dto(raw);
  }

  @protected
  RequestDto dco_decode_box_autoadd_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_request_dto(raw);
  }

  @protected
  ConnectParamsDto dco_decode_connect_params_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ConnectParamsDto(
      profileJson: dco_decode_String(arr[0]),
      user: dco_decode_String(arr[1]),
      routeMode: dco_decode_String(arr[2]),
      cidrs: dco_decode_list_String(arr[3]),
      captureDns: dco_decode_bool(arr[4]),
      tunAddress: dco_decode_String(arr[5]),
    );
  }

  @protected
  ErrorKindDto dco_decode_error_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ErrorKindDto.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IncomingDto dco_decode_incoming_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return IncomingDto_Ack(id: dco_decode_u_64(raw[1]));
      case 1:
        return IncomingDto_Error(
          id: dco_decode_u_64(raw[1]),
          kind: dco_decode_error_kind_dto(raw[2]),
          message: dco_decode_String(raw[3]),
        );
      case 2:
        return IncomingDto_State(state: dco_decode_String(raw[1]));
      case 3:
        return IncomingDto_Stats(
          bytesUp: dco_decode_u_64(raw[1]),
          bytesDown: dco_decode_u_64(raw[2]),
          activeFlows: dco_decode_u_32(raw[3]),
          flowsFailed: dco_decode_u_64(raw[4]),
          dnsQueries: dco_decode_u_64(raw[5]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProbeChoice dco_decode_probe_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ProbeChoice_First();
      case 1:
        return ProbeChoice_Second(detail: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ProbeDto dco_decode_probe_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProbeDto(
      name: dco_decode_String(arr[0]),
      count: dco_decode_u_32(arr[1]),
      maybe: dco_decode_opt_String(arr[2]),
      items: dco_decode_list_String(arr[3]),
      choice: dco_decode_probe_choice(arr[4]),
    );
  }

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return ProfileDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      protocol: dco_decode_String(arr[2]),
      host: dco_decode_String(arr[3]),
      port: dco_decode_u_16(arr[4]),
      authKind: dco_decode_String(arr[5]),
      authSecretSource: dco_decode_String(arr[6]),
      authPassphraseSource: dco_decode_opt_String(arr[7]),
      peerPublicKey: dco_decode_opt_String(arr[8]),
      cipher: dco_decode_opt_String(arr[9]),
      dnsMode: dco_decode_String(arr[10]),
      dnsServers: dco_decode_list_String(arr[11]),
      dohSni: dco_decode_opt_String(arr[12]),
      dohPath: dco_decode_opt_String(arr[13]),
      splitTunnel: dco_decode_String(arr[14]),
      splitTunnelApps: dco_decode_list_String(arr[15]),
      killSwitch: dco_decode_bool(arr[16]),
    );
  }

  @protected
  RequestDto dco_decode_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return RequestDto_Hello(id: dco_decode_u_64(raw[1]));
      case 1:
        return RequestDto_Connect(
          id: dco_decode_u_64(raw[1]),
          params: dco_decode_box_autoadd_connect_params_dto(raw[2]),
        );
      case 2:
        return RequestDto_Disconnect(id: dco_decode_u_64(raw[1]));
      case 3:
        return RequestDto_GetStatus(id: dco_decode_u_64(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConnectParamsDto sse_decode_box_autoadd_connect_params_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_connect_params_dto(deserializer));
  }

  @protected
  ProbeDto sse_decode_box_autoadd_probe_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_probe_dto(deserializer));
  }

  @protected
  ProfileDto sse_decode_box_autoadd_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile_dto(deserializer));
  }

  @protected
  RequestDto sse_decode_box_autoadd_request_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_request_dto(deserializer));
  }

  @protected
  ConnectParamsDto sse_decode_connect_params_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_profileJson = sse_decode_String(deserializer);
    var var_user = sse_decode_String(deserializer);
    var var_routeMode = sse_decode_String(deserializer);
    var var_cidrs = sse_decode_list_String(deserializer);
    var var_captureDns = sse_decode_bool(deserializer);
    var var_tunAddress = sse_decode_String(deserializer);
    return ConnectParamsDto(
      profileJson: var_profileJson,
      user: var_user,
      routeMode: var_routeMode,
      cidrs: var_cidrs,
      captureDns: var_captureDns,
      tunAddress: var_tunAddress,
    );
  }

  @protected
  ErrorKindDto sse_decode_error_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ErrorKindDto.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IncomingDto sse_decode_incoming_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_id = sse_decode_u_64(deserializer);
        return IncomingDto_Ack(id: var_id);
      case 1:
        var var_id = sse_decode_u_64(deserializer);
        var var_kind = sse_decode_error_kind_dto(deserializer);
        var var_message = sse_decode_String(deserializer);
        return IncomingDto_Error(
          id: var_id,
          kind: var_kind,
          message: var_message,
        );
      case 2:
        var var_state = sse_decode_String(deserializer);
        return IncomingDto_State(state: var_state);
      case 3:
        var var_bytesUp = sse_decode_u_64(deserializer);
        var var_bytesDown = sse_decode_u_64(deserializer);
        var var_activeFlows = sse_decode_u_32(deserializer);
        var var_flowsFailed = sse_decode_u_64(deserializer);
        var var_dnsQueries = sse_decode_u_64(deserializer);
        return IncomingDto_Stats(
          bytesUp: var_bytesUp,
          bytesDown: var_bytesDown,
          activeFlows: var_activeFlows,
          flowsFailed: var_flowsFailed,
          dnsQueries: var_dnsQueries,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProbeChoice sse_decode_probe_choice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ProbeChoice_First();
      case 1:
        var var_detail = sse_decode_String(deserializer);
        return ProbeChoice_Second(detail: var_detail);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ProbeDto sse_decode_probe_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    var var_maybe = sse_decode_opt_String(deserializer);
    var var_items = sse_decode_list_String(deserializer);
    var var_choice = sse_decode_probe_choice(deserializer);
    return ProbeDto(
      name: var_name,
      count: var_count,
      maybe: var_maybe,
      items: var_items,
      choice: var_choice,
    );
  }

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_authKind = sse_decode_String(deserializer);
    var var_authSecretSource = sse_decode_String(deserializer);
    var var_authPassphraseSource = sse_decode_opt_String(deserializer);
    var var_peerPublicKey = sse_decode_opt_String(deserializer);
    var var_cipher = sse_decode_opt_String(deserializer);
    var var_dnsMode = sse_decode_String(deserializer);
    var var_dnsServers = sse_decode_list_String(deserializer);
    var var_dohSni = sse_decode_opt_String(deserializer);
    var var_dohPath = sse_decode_opt_String(deserializer);
    var var_splitTunnel = sse_decode_String(deserializer);
    var var_splitTunnelApps = sse_decode_list_String(deserializer);
    var var_killSwitch = sse_decode_bool(deserializer);
    return ProfileDto(
      id: var_id,
      name: var_name,
      protocol: var_protocol,
      host: var_host,
      port: var_port,
      authKind: var_authKind,
      authSecretSource: var_authSecretSource,
      authPassphraseSource: var_authPassphraseSource,
      peerPublicKey: var_peerPublicKey,
      cipher: var_cipher,
      dnsMode: var_dnsMode,
      dnsServers: var_dnsServers,
      dohSni: var_dohSni,
      dohPath: var_dohPath,
      splitTunnel: var_splitTunnel,
      splitTunnelApps: var_splitTunnelApps,
      killSwitch: var_killSwitch,
    );
  }

  @protected
  RequestDto sse_decode_request_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_id = sse_decode_u_64(deserializer);
        return RequestDto_Hello(id: var_id);
      case 1:
        var var_id = sse_decode_u_64(deserializer);
        var var_params = sse_decode_box_autoadd_connect_params_dto(
          deserializer,
        );
        return RequestDto_Connect(id: var_id, params: var_params);
      case 2:
        var var_id = sse_decode_u_64(deserializer);
        return RequestDto_Disconnect(id: var_id);
      case 3:
        var var_id = sse_decode_u_64(deserializer);
        return RequestDto_GetStatus(id: var_id);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_connect_params_dto(
    ConnectParamsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_connect_params_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_probe_dto(
    ProbeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_probe_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_profile_dto(
    ProfileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_request_dto(
    RequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_request_dto(self, serializer);
  }

  @protected
  void sse_encode_connect_params_dto(
    ConnectParamsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.profileJson, serializer);
    sse_encode_String(self.user, serializer);
    sse_encode_String(self.routeMode, serializer);
    sse_encode_list_String(self.cidrs, serializer);
    sse_encode_bool(self.captureDns, serializer);
    sse_encode_String(self.tunAddress, serializer);
  }

  @protected
  void sse_encode_error_kind_dto(ErrorKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_incoming_dto(IncomingDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case IncomingDto_Ack(id: final id):
        sse_encode_i_32(0, serializer);
        sse_encode_u_64(id, serializer);
      case IncomingDto_Error(
        id: final id,
        kind: final kind,
        message: final message,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_64(id, serializer);
        sse_encode_error_kind_dto(kind, serializer);
        sse_encode_String(message, serializer);
      case IncomingDto_State(state: final state):
        sse_encode_i_32(2, serializer);
        sse_encode_String(state, serializer);
      case IncomingDto_Stats(
        bytesUp: final bytesUp,
        bytesDown: final bytesDown,
        activeFlows: final activeFlows,
        flowsFailed: final flowsFailed,
        dnsQueries: final dnsQueries,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_u_64(bytesUp, serializer);
        sse_encode_u_64(bytesDown, serializer);
        sse_encode_u_32(activeFlows, serializer);
        sse_encode_u_64(flowsFailed, serializer);
        sse_encode_u_64(dnsQueries, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_probe_choice(ProbeChoice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ProbeChoice_First():
        sse_encode_i_32(0, serializer);
      case ProbeChoice_Second(detail: final detail):
        sse_encode_i_32(1, serializer);
        sse_encode_String(detail, serializer);
    }
  }

  @protected
  void sse_encode_probe_dto(ProbeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.count, serializer);
    sse_encode_opt_String(self.maybe, serializer);
    sse_encode_list_String(self.items, serializer);
    sse_encode_probe_choice(self.choice, serializer);
  }

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.authKind, serializer);
    sse_encode_String(self.authSecretSource, serializer);
    sse_encode_opt_String(self.authPassphraseSource, serializer);
    sse_encode_opt_String(self.peerPublicKey, serializer);
    sse_encode_opt_String(self.cipher, serializer);
    sse_encode_String(self.dnsMode, serializer);
    sse_encode_list_String(self.dnsServers, serializer);
    sse_encode_opt_String(self.dohSni, serializer);
    sse_encode_opt_String(self.dohPath, serializer);
    sse_encode_String(self.splitTunnel, serializer);
    sse_encode_list_String(self.splitTunnelApps, serializer);
    sse_encode_bool(self.killSwitch, serializer);
  }

  @protected
  void sse_encode_request_dto(RequestDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RequestDto_Hello(id: final id):
        sse_encode_i_32(0, serializer);
        sse_encode_u_64(id, serializer);
      case RequestDto_Connect(id: final id, params: final params):
        sse_encode_i_32(1, serializer);
        sse_encode_u_64(id, serializer);
        sse_encode_box_autoadd_connect_params_dto(params, serializer);
      case RequestDto_Disconnect(id: final id):
        sse_encode_i_32(2, serializer);
        sse_encode_u_64(id, serializer);
      case RequestDto_GetStatus(id: final id):
        sse_encode_i_32(3, serializer);
        sse_encode_u_64(id, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
