// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto/profile.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> androidStageProfile({
  required ProfileDto dto,
  required String user,
  required List<SecretPair> secrets,
}) => RustLib.instance.api.crateApiAndroidAndroidStageProfile(
  dto: dto,
  user: user,
  secrets: secrets,
);

Future<EngineStatusDto> androidStatus() =>
    RustLib.instance.api.crateApiAndroidAndroidStatus();

Future<EngineStatsDto> androidStats() =>
    RustLib.instance.api.crateApiAndroidAndroidStats();

/// Counters, mirroring the desktop `Stats` frame so `ConnectionModel`
/// consumes one shape on both platforms.
class EngineStatsDto {
  final BigInt bytesUp;
  final BigInt bytesDown;
  final BigInt activeFlows;
  final BigInt flowsFailed;
  final BigInt dnsQueries;

  const EngineStatsDto({
    required this.bytesUp,
    required this.bytesDown,
    required this.activeFlows,
    required this.flowsFailed,
    required this.dnsQueries,
  });

  @override
  int get hashCode =>
      bytesUp.hashCode ^
      bytesDown.hashCode ^
      activeFlows.hashCode ^
      flowsFailed.hashCode ^
      dnsQueries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineStatsDto &&
          runtimeType == other.runtimeType &&
          bytesUp == other.bytesUp &&
          bytesDown == other.bytesDown &&
          activeFlows == other.activeFlows &&
          flowsFailed == other.flowsFailed &&
          dnsQueries == other.dnsQueries;
}

/// Engine state, flattened for the UI.
///
/// `detail` carries the failure reason and is empty otherwise. Kept separate
/// from `state` so the UI can show a reason without parsing a string.
class EngineStatusDto {
  final String state;
  final String detail;

  const EngineStatusDto({required this.state, required this.detail});

  @override
  int get hashCode => state.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineStatusDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          detail == other.detail;
}

/// A secret the app resolved, paired with the reference the profile uses.
///
/// `kind` is `"file"` or `"env"`, matching `SecretRef`'s two forms, and `key`
/// is the path or variable name the profile names. The engine looks secrets
/// up by reference, so both halves are needed to match them.
class SecretPair {
  final String kind;
  final String key;
  final String value;

  const SecretPair({
    required this.kind,
    required this.key,
    required this.value,
  });

  @override
  int get hashCode => kind.hashCode ^ key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecretPair &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          key == other.key &&
          value == other.value;
}
