// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto/profile.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_cipher`, `check_pairing`, `parse`

/// Parses a profile JSON document into a UI-shaped DTO.
///
/// Returns a description of the profile, never its secret material.
///
/// The error deliberately omits serde's message: its `Display` quotes keys
/// and enum tags from the offending input, and the input is a profile.
Future<ProfileDto> parseProfile({required String json}) =>
    RustLib.instance.api.crateApiConfigParseProfile(json: json);

/// Renders a DTO back to the canonical on-disk profile JSON.
///
/// Spec §9 asks for "portable import/export". Import is `parse_profile`;
/// this is export, so a profile can leave the app and come back unchanged.
/// §4 puts in-app *editing* out of scope, not portability.
///
/// The output is a profile document, so it names where secrets live and
/// never carries them — exactly what `parse_profile` accepted.
Future<String> exportProfile({required ProfileDto dto}) =>
    RustLib.instance.api.crateApiConfigExportProfile(dto: dto);

/// A fresh profile id.
///
/// Generated in Rust so the id format stays a property of the schema rather
/// than something Dart reimplements — the same reasoning as parse_profile
/// (P1a-1). A v4 UUID formatted the way `ServerProfile` expects to read it
/// back.
Future<String> newProfileId() =>
    RustLib.instance.api.crateApiConfigNewProfileId();

/// Checks a profile the UI is about to save, without touching its secret.
///
/// Deliberately NOT `ServerProfile::validate`: that resolves every
/// `SecretRef` through a `SecretStore`, which would have the app read key
/// material it has no business reading. This checks the shape only — the
/// helper re-validates properly at connect time, as the caller's uid.
Future<void> checkProfile({required ProfileDto dto}) =>
    RustLib.instance.api.crateApiConfigCheckProfile(dto: dto);

/// One-line summary for the profiles list.
Future<String> profileSummary({required ProfileDto dto}) =>
    RustLib.instance.api.crateApiConfigProfileSummary(dto: dto);

/// The cipher names a Shadowsocks profile may use.
///
/// Exists so the editor's dropdown can be checked against the core's own
/// list rather than against a second copy of it. Offering a cipher the core
/// refuses is advice the user follows and that then fails as unknown -- a bug
/// the core's own list shipped with once already.
Future<List<String>> offeredCiphers() =>
    RustLib.instance.api.crateApiConfigOfferedCiphers();

/// Turns an `ss://` link into a profile the editor can show.
///
/// Returns the profile WITHOUT its password: `auth_secret_source` is left
/// empty and the caller writes the password to a `0600` file, then fills it
/// in. Returning the password inside the DTO would put a credential in a
/// value that crosses into Dart and gets rendered on screen — the one thing
/// this type exists not to do.
///
/// The password comes back separately from [`ss_uri_password`], which the
/// caller feeds straight to the secret writer without ever storing it.
///
/// The error deliberately says nothing about the link. An `ss://` URI *is*
/// the credential, so quoting any part of it — the blob, a fragment, "near
/// here" — puts a live password in a message that reaches a root-owned log
/// and comes back over the wire.
///
/// A cipher this build cannot construct is refused here, BEFORE the DTO
/// exists. `parse_ss_uri` deliberately does not check the method — the cipher
/// list has one owner — so this is the first place that can. Doing it later
/// was worth a crash: the caller writes the password to a `0600` file the
/// moment the import succeeds and only then puts the cipher in front of a
/// dropdown that asserts its value is one of its items, so an Outline key
/// (`2022-blake3-aes-256-gcm`) destroyed the editor with the credential
/// already on disk.
Future<ProfileDto> importSsUri({required String uri}) =>
    RustLib.instance.api.crateApiConfigImportSsUri(uri: uri);

/// The password from an `ss://` link, for the caller to write to a `0600`
/// file. Separate from [`import_ss_uri`] so the credential never travels
/// inside a struct that anything renders.
Future<String> ssUriPassword({required String uri}) =>
    RustLib.instance.api.crateApiConfigSsUriPassword(uri: uri);

/// What a `file:` secret's *value* is, given the file's bytes.
///
/// Not the raw bytes. `FileSecretStore::resolve` — the thing the helper
/// actually connects with — strips one trailing line ending, because a
/// password written by `echo hunter2 > pw` means `hunter2` while a PEM private
/// key's own final newline is content. That rule has exactly one owner, in the
/// core, and this hands it to Dart rather than letting a second copy grow
/// there. A second copy is free to drift, on a rule whose entire purpose is
/// that two components agree about the user's password: the app read the file
/// itself and copied an `ss://` link carrying `hunter2\n`, which every other
/// client then derives a different key from, and Shadowsocks has no handshake
/// in which to report it.
///
/// Bytes in, because a credential is bytes: a binary pre-shared key or a
/// DER-encoded private key is not text, and `read_to_string` — like Dart's
/// `readAsStringSync` — answers one with a decoder's complaint about byte
/// offsets. A refusal is the honest outcome for anything that needs a
/// `String`, but it should be a sentence the app wrote. Nothing of the file
/// appears in it.
Future<String> fileSecretValue({required List<int> bytes}) =>
    RustLib.instance.api.crateApiConfigFileSecretValue(bytes: bytes);

/// Renders a Shadowsocks profile as an `ss://` link the user can copy.
///
/// **The returned String carries the password.** It is what every other
/// Shadowsocks client accepts, which is the point, and there is no
/// secret-free form of an `ss://` link. The caller is responsible for asking
/// before putting it anywhere shared.
///
/// The password comes in as a parameter: the app runs as the user and the
/// secret file is the user's own, so Dart reads it. This crate does not open
/// files on the app's behalf.
///
/// Refusals name no field of the profile. Every one of them is
/// caller-supplied and this error crosses back over the wire.
///
/// **This is the well-formedness guard.** `render_ss_uri` is total, but not
/// every input renders something a Shadowsocks client can read: an empty host,
/// port 0, an IPv6 or bracketed host, an empty cipher and an empty password
/// each produce a link that this build's own `parse_ss_uri` then refuses.
/// `ProfileDto` enforces none of those — its fields are a `String`, a `u16` and
/// an `Option<String>` — and nothing upstream is guaranteed to have screened
/// them. Without these checks the user copies something no client can use.
///
/// It is deliberately NOT a round-trip guard, and that is the one asymmetry
/// with [`import_ss_uri`], which calls [`check_cipher`]. A profile written by
/// the CLI may name `2022-blake3-aes-256-gcm` — today's default server cipher —
/// and the link this renders for it is perfectly well formed and perfectly
/// usable in Outline or shadowsocks-rust. That it will not import back into
/// *this* build is a limitation of this build's cipher feature set, not a
/// defect in the link, and "copy as a link" exists precisely so a profile can
/// be used in another client. Refusing here would withhold a working link from
/// a profile this app cannot connect with OR edit — a dead end, in place of the
/// one gesture that still gets the user's own credential out. The cipher name
/// is not secret and the link says it plainly, so nothing is hidden by letting
/// it through. `a_link_is_rendered_for_a_cipher_this_build_cannot_speak` pins
/// this decision, including the half that makes it a decision: our own import
/// still refuses it.
Future<String> exportSsUri({
  required ProfileDto dto,
  required String password,
}) => RustLib.instance.api.crateApiConfigExportSsUri(
  dto: dto,
  password: password,
);
