// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto/profile.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Parses a profile JSON document into a UI-shaped DTO.
///
/// Returns a description of the profile, never its secret material.
///
/// The error deliberately omits serde's message: its `Display` quotes keys
/// and enum tags from the offending input, and the input is a profile.
Future<ProfileDto> parseProfile({required String json}) =>
    RustLib.instance.api.crateApiConfigParseProfile(json: json);

/// Renders a DTO back to the canonical on-disk profile JSON.
///
/// Spec §9 asks for "portable import/export". Import is `parse_profile`;
/// this is export, so a profile can leave the app and come back unchanged.
/// §4 puts in-app *editing* out of scope, not portability.
///
/// The output is a profile document, so it names where secrets live and
/// never carries them — exactly what `parse_profile` accepted.
Future<String> exportProfile({required ProfileDto dto}) =>
    RustLib.instance.api.crateApiConfigExportProfile(dto: dto);

/// One-line summary for the profiles list.
Future<String> profileSummary({required ProfileDto dto}) =>
    RustLib.instance.api.crateApiConfigProfileSummary(dto: dto);
