// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'probe.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Round-trips its argument. Dart asserts the value survives unchanged.
Future<ProbeDto> echoProbe({required ProbeDto input}) =>
    RustLib.instance.api.crateApiProbeEchoProbe(input: input);

@freezed
sealed class ProbeChoice with _$ProbeChoice {
  const ProbeChoice._();

  const factory ProbeChoice.first() = ProbeChoice_First;
  const factory ProbeChoice.second({required String detail}) =
      ProbeChoice_Second;
}

class ProbeDto {
  final String name;
  final int count;
  final String? maybe;
  final List<String> items;
  final ProbeChoice choice;

  const ProbeDto({
    required this.name,
    required this.count,
    this.maybe,
    required this.items,
    required this.choice,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      count.hashCode ^
      maybe.hashCode ^
      items.hashCode ^
      choice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProbeDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          count == other.count &&
          maybe == other.maybe &&
          items == other.items &&
          choice == other.choice;
}
