// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'protocol.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Serializes a request to a single wire line, without the trailing newline.
Future<String> encodeRequest({required RequestDto req}) =>
    RustLib.instance.api.crateApiProtocolEncodeRequest(req: req);

/// Parses one wire line.
///
/// Unknown message types are an error, never a default — a helper newer than
/// the app must be ignored deliberately rather than silently. Both `Response`
/// and `Event` are `#[serde(tag = "type")]`, so an unrecognised tag fails
/// both attempts.
Future<IncomingDto> decodeMessage({required String line}) =>
    RustLib.instance.api.crateApiProtocolDecodeMessage(line: line);

/// The protocol version this build speaks.
Future<int> protocolVersion() =>
    RustLib.instance.api.crateApiProtocolProtocolVersion();

/// Mirrors [`protocol::ConnectParams`] field for field. Every field is a
/// `String` or a primitive, so nothing here needs FRB to model a core type.
class ConnectParamsDto {
  final String profileJson;
  final String user;

  /// `"test"` or `"default"`.
  final String routeMode;

  /// Only meaningful when `route_mode == "test"`.
  final List<String> cidrs;
  final bool captureDns;
  final String tunAddress;

  const ConnectParamsDto({
    required this.profileJson,
    required this.user,
    required this.routeMode,
    required this.cidrs,
    required this.captureDns,
    required this.tunAddress,
  });

  @override
  int get hashCode =>
      profileJson.hashCode ^
      user.hashCode ^
      routeMode.hashCode ^
      cidrs.hashCode ^
      captureDns.hashCode ^
      tunAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectParamsDto &&
          runtimeType == other.runtimeType &&
          profileJson == other.profileJson &&
          user == other.user &&
          routeMode == other.routeMode &&
          cidrs == other.cidrs &&
          captureDns == other.captureDns &&
          tunAddress == other.tunAddress;
}

/// The machine-readable failure contract. The UI branches on this; `message`
/// is for humans and must never be parsed.
enum ErrorKindDto {
  versionMismatch,
  unauthorized,
  secretNotPermitted,
  alreadyConnected,
  notConnected,
  authFailed,
  badRequest,
  internal,
}

@freezed
sealed class IncomingDto with _$IncomingDto {
  const IncomingDto._();

  const factory IncomingDto.ack({required BigInt id}) = IncomingDto_Ack;
  const factory IncomingDto.error({
    required BigInt id,
    required ErrorKindDto kind,
    required String message,
  }) = IncomingDto_Error;
  const factory IncomingDto.state({required String state}) = IncomingDto_State;

  /// Field types match [`protocol::StatsSnapshot`] exactly — `flows_failed`
  /// is a `u64` there, and narrowing it here would silently truncate.
  const factory IncomingDto.stats({
    required BigInt bytesUp,
    required BigInt bytesDown,
    required int activeFlows,
    required BigInt flowsFailed,
    required BigInt dnsQueries,
  }) = IncomingDto_Stats;
}

@freezed
sealed class RequestDto with _$RequestDto {
  const RequestDto._();

  const factory RequestDto.hello({required BigInt id}) = RequestDto_Hello;
  const factory RequestDto.connect({
    required BigInt id,
    required ConnectParamsDto params,
  }) = RequestDto_Connect;
  const factory RequestDto.disconnect({required BigInt id}) =
      RequestDto_Disconnect;
  const factory RequestDto.getStatus({required BigInt id}) =
      RequestDto_GetStatus;
}
