// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A profile in the shape the UI wants: flat, and made of types
/// `flutter_rust_bridge` models without persuasion.
///
/// The FFI crate owns this rather than exporting `ServerProfile` directly.
/// The core type holds a `Uuid`, `IpAddr`s and nested tagged enums; binding
/// Dart to it would let any core change break codegen, and would start
/// shaping the core around what FRB finds convenient (spec §9, D7).
///
/// **It describes where secrets live and never what they are.** This value
/// crosses into Dart, gets rendered on screen, and its `profile_json` reaches
/// the helper over a socket.
class ProfileDto {
  final String id;
  final String name;
  final String protocol;
  final String host;
  final int port;

  /// `"password"`, `"private_key"` or `"preshared_key"`.
  final String authKind;

  /// Where the material lives — `"file:/path"` or `"env:NAME"` — never the
  /// material itself.
  final String authSecretSource;

  /// Present only for `private_key` with a passphrase, and again only ever
  /// a location.
  final String? authPassphraseSource;

  /// Public by definition for `preshared_key`; not a secret.
  final String? peerPublicKey;
  final String dnsMode;
  final List<String> dnsServers;
  final String? dohSni;
  final String? dohPath;
  final String splitTunnel;
  final List<String> splitTunnelApps;
  final bool killSwitch;

  const ProfileDto({
    required this.id,
    required this.name,
    required this.protocol,
    required this.host,
    required this.port,
    required this.authKind,
    required this.authSecretSource,
    this.authPassphraseSource,
    this.peerPublicKey,
    required this.dnsMode,
    required this.dnsServers,
    this.dohSni,
    this.dohPath,
    required this.splitTunnel,
    required this.splitTunnelApps,
    required this.killSwitch,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      protocol.hashCode ^
      host.hashCode ^
      port.hashCode ^
      authKind.hashCode ^
      authSecretSource.hashCode ^
      authPassphraseSource.hashCode ^
      peerPublicKey.hashCode ^
      dnsMode.hashCode ^
      dnsServers.hashCode ^
      dohSni.hashCode ^
      dohPath.hashCode ^
      splitTunnel.hashCode ^
      splitTunnelApps.hashCode ^
      killSwitch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          protocol == other.protocol &&
          host == other.host &&
          port == other.port &&
          authKind == other.authKind &&
          authSecretSource == other.authSecretSource &&
          authPassphraseSource == other.authPassphraseSource &&
          peerPublicKey == other.peerPublicKey &&
          dnsMode == other.dnsMode &&
          dnsServers == other.dnsServers &&
          dohSni == other.dohSni &&
          dohPath == other.dohPath &&
          splitTunnel == other.splitTunnel &&
          splitTunnelApps == other.splitTunnelApps &&
          killSwitch == other.killSwitch;
}
